### ISSUE TITLE
Great idea for a npm-friendly restart tool but can it be upgraded to work with latest electron?

### ISSUE THREAD

**Issue by mmc41** [simonhochrein/electromon#1]
I have installed electromon but the npm install downloads old electron stuff and the executable gives an error when using latest electron getting started example. Could this tool be upgraded not to bind to a specific old electron version and work with the latest electron ?

**Comment by simonhochrein** [comment]
Yes, the path to the electron binary can be changed to the local electron path and fallback to a newer version

**Comment by simonhochrein** [comment]
https://github.com/simonhochrein/electromon/blob/master/index.js#L2
requiring that library sets the path to the binary
Pull requests welcome 😉

**Comment by mmc41** [comment]
I just tried "electromon ./YOUR_FILE_HERE" and it failed. 
BTW. The npm electron-prebuilt has been renamed to electron

**Comment by simonhochrein** [comment]
Could I see your complete command without any replacements?

**Comment by mmc41** [comment]
This is what I did - where I got errors:
cloned the electron quick start app into my-project-dir
cd my-project-dir
electromon .

**Comment by mmc41** [comment]
in addition I noticed that installing electromon with -g also downloaded and installed a very old version of electron. I think you should change that so there is no explicit dependency but just uses what is installed already.

**Comment by simonhochrein** [comment]
That is because of this:
https://github.com/simonhochrein/electromon/blob/master/package.json#L12
Could I see your `package.json` file?

**Comment by mmc41** [comment]
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "private": true,
  "main": "bin/main.js",
  "scripts": {
    "start": "npm-run-all --race --parallel start:electron watch:tsc",
    "start:electron": "electron .",
    "watch:tsc": "tsc -w"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/electron/electron-quick-start.git"
  },
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "bugs": {
    "url": "https://github.com/electron/electron-quick-start/issues"
  },
  "homepage": "https://github.com/electron/electron-quick-start#readme",
  "devDependencies": {
    "electron": "^1.3.4",
    "npm-run-all": ">= 2.3.0"
  },
  "engines": {
    "node": ">=6.3.0",
    "npm": "~3.0.0"
  }
}

**Comment by simonhochrein** [comment]
The program runs the main file section of your package.json file with electron
The documentation is a bit wrong
Hope this helps

**Comment by simonhochrein** [comment]
Haven't worked on these projects in a bit, any help would be appreciated.

**Comment by simonhochrein** [comment]
I set the package to use latest electron

**Comment by SelaO** [comment]
It does start the app now but when I save a change it says it's restarting but it just closes.
