### ISSUE TITLE
PWD doesn't exist on windows

### ISSUE THREAD

**Issue by SelaO** [simonhochrein/electromon#3]
The command pwd doesn't exist on windows so this doesn't work.

**Comment by simonhochrein** [comment]
I built this app mainly for Mac and have not updated it in a very long time.
I will try to get around to this soon.
Pull requests would be appreciated.

**Comment by simonhochrein** [comment]
could you update the package and try again?

**Comment by SelaO** [comment]
It does start the app now but when I save a change it says it's restarting but it just closes.

**Comment by simonhochrein** [comment]
Hello, I just fixed it. If you could test again that would be great.

**Comment by SelaO** [comment]
Now it closes and reopens. 

It's not really hot reloading though, still better than doing it manually. 

Thanks.

**Comment by simonhochrein** [comment]
This module is not for hot reloading only restarting. For reloading I recommend web pack for the front end and using the electromon ignore file.

**Comment by simonhochrein** [comment]
Closing as the issue seems to be fixed
