### ISSUE TITLE
Does not read command line arguements

### ISSUE THREAD

**Issue by milonti** [simonhochrein/electromon#4]
Trying to use this to help w/ app development. It doesn't seem to read in cmd parameters. So it just keeps throwing an error telling me it can't find an electron app at the directory level. Shouldn't it read in something from process.argv to read what file the user is trying to run?

**Comment by simonhochrein** [comment]
I see that, let me see if I can fix that quick

**Comment by simonhochrein** [comment]
Ok, it should be fixed, let me know if it works

**Comment by milonti** [comment]
Looks like its working now! Thanks for the quick turn-around :D
